/* Creative Items */
//Dank Null
mods.extendedcrafting.TableCrafting.addShaped(0, <danknull:dank_null_6>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <mysticalagradditions:stuff:69>], 
	[<danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>], 
	[<danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>], 
	[<danknull:dank_null_panel_3>, <danknull:dank_null_panel_3>, <danknull:dank_null_panel_3>, <danknull:dank_null_panel_5>, <ore:ingotInfinity>, <danknull:dank_null_panel_5>, <danknull:dank_null_panel_4>, <danknull:dank_null_panel_4>, <danknull:dank_null_panel_4>], 
	[<danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>], 
	[<danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>], 
	[<mysticalagradditions:stuff:69>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <danknull:dank_null_panel_0>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Mana Tablet
mods.extendedcrafting.TableCrafting.addShaped(0, <botania:manatablet>.withTag({mana: 500000, creative: 1 as byte}), [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:runeWaterB>, <ore:runeFireB>, <ore:runeEarthB>, <ore:runeAirB>, <ore:runeSpringB>, <ore:runeSummerB>, <ore:runeAutumnB>, <mysticalagradditions:stuff:69>], 
	[<ore:runeEnvyB>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <ore:runePrideB>], 
	[<botania:livingrock>, <botania:manatablet>, <ore:manaPearl>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:manaPearl>, <botania:manatablet>, <botania:livingrock>], 
	[<botania:livingrock>, <botania:manatablet>, <ore:manaDiamond>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:manaDiamond>, <botania:manatablet>, <botania:livingrock>], 
	[<botania:livingrock>, <botania:manatablet>, <ore:ingotManasteel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotManasteel>, <botania:manatablet>, <botania:livingrock>], 
	[<botanicadds:rune_tp>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botania:livingrock>, <botanicadds:rune_energy>], 
	[<mysticalagradditions:stuff:69>, <ore:runeWinterB>, <ore:runeManaB>, <ore:runeLustB>, <ore:runeGluttonyB>, <ore:runeGreedB>, <ore:runeSlothB>, <ore:runeWrathB>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//The Everlasting Guilty Pool
mods.extendedcrafting.TableCrafting.addShaped(0, <botania:pool:1>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <botania:manatablet>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <botanicadds:pool_dreaming>, <mysticalagradditions:stuff:69>], 
	[<botanicadds:pool_dreaming>, <ore:manaPearl>, <ore:manaDiamond>, <ore:ingotElvenElementium>, <ore:elvenDragonstone>, <ore:ingotElvenElementium>, <ore:manaDiamond>, <ore:manaPearl>, <botanicadds:pool_dreaming>], 
	[<ore:ingotManasteel>, <ore:manaPearl>, <ore:manaDiamond>, <ore:eternalLifeEssence>, <ore:eternalLifeEssence>, <ore:eternalLifeEssence>, <ore:manaDiamond>, <ore:manaPearl>, <ore:ingotManasteel>], 
	[<ore:ingotManasteel>, <ore:manaPearl>, <ore:manaDiamond>, <ore:eternalLifeEssence>, <ore:ingotInfinity>, <ore:eternalLifeEssence>, <ore:manaDiamond>, <ore:manaPearl>, <ore:ingotManasteel>], 
	[<ore:ingotManasteel>, <ore:manaPearl>, <ore:manaDiamond>, <ore:eternalLifeEssence>, <ore:eternalLifeEssence>, <ore:eternalLifeEssence>, <ore:manaDiamond>, <ore:manaPearl>, <ore:ingotManasteel>], 
	[<botania:pool:3>, <ore:manaPearl>, <ore:manaDiamond>, <ore:elvenPixieDust>, <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:manaDiamond>, <ore:manaPearl>, <botania:pool:3>], 
	[<mysticalagradditions:stuff:69>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Model Learner
mods.extendedcrafting.TableCrafting.addShaped(0, <deepmoblearning:creative_model_learner>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <deepmoblearning:data_model_zombie>, <deepmoblearning:data_model_skeleton>, <deepmoblearning:data_model_creeper>, <deepmoblearning:data_model_spider>, <deepmoblearning:data_model_slime>, <deepmoblearning:data_model_witch>, <deepmoblearning:data_model_blaze>, <mysticalagradditions:stuff:69>], 
	[<deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>], 
	[<deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>], 
	[<deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>, <ore:ingotInfinity>, <deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>, <deepmoblearning:living_matter_extraterrestrial>], 
	[<deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>, <deepmoblearning:living_matter_hellish>], 
	[<deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>, <deepmoblearning:living_matter_overworldian>], 
	[<mysticalagradditions:stuff:69>, <deepmoblearning:data_model_ghast>, <deepmoblearning:data_model_wither_skeleton>, <deepmoblearning:data_model_enderman>, <deepmoblearning:data_model_wither>, <deepmoblearning:data_model_dragon>, <deepmoblearning:data_model_shulker>, <deepmoblearning:data_model_guardian>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Flux Capacitor
mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:draconium_capacitor:2>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <mysticalagradditions:stuff:69>], 
	[<ore:ingotDraconiumAwakened>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconium>, <draconicevolution:draconium_capacitor>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconiumAwakened>], 
	[<ore:ingotDraconium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <draconicevolution:draconium_capacitor:1>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotDraconium>], 
	[<ore:ingotDraconium>, <ore:ingotCosmicNeutronium>, <draconicevolution:draconium_capacitor>, <draconicevolution:draconium_capacitor:1>, <ore:ingotInfinity>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor>, <ore:ingotCosmicNeutronium>, <ore:ingotDraconium>], 
	[<ore:ingotDraconium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <draconicevolution:draconium_capacitor:1>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotDraconium>], 
	[<ore:ingotDraconiumAwakened>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconium>, <draconicevolution:draconium_capacitor>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconium>, <ore:ingotDraconiumAwakened>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Storage Disk
mods.extendedcrafting.TableCrafting.addShaped(0, <refinedstorage:storage_disk:4>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <mysticalagradditions:stuff:69>], 
	[<refinedstorage:storage_part:1>, <refinedstorage:storage_part:2>, <refinedstorage:storage_part:2>, <rebornstorage:storagepart>, <rebornstorage:storagepart:3>, <rebornstorage:storagepart:1>, <refinedstorage:storage_part:2>, <refinedstorage:storage_part:2>, <refinedstorage:storage_part:1>], 
	[<refinedstorage:storage_part:1>, <refinedstorage:storage_part:2>, <rebornstorage:storagepart>, <rebornstorage:storagepart:3>, <refinedstorage:storage_housing>, <rebornstorage:storagepart:3>, <rebornstorage:storagepart:1>, <refinedstorage:storage_part:2>, <refinedstorage:storage_part:1>], 
	[<refinedstorage:storage_part:1>, <rebornstorage:storagepart>, <rebornstorage:storagepart:3>, <refinedstorage:storage_housing>, <ore:ingotInfinity>, <refinedstorage:storage_housing>, <rebornstorage:storagepart:3>, <rebornstorage:storagepart:1>, <refinedstorage:storage_part:1>], 
	[<refinedstorage:storage_part:1>, <refinedstorage:storage_part:3>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_part:3>, <refinedstorage:storage_part:1>], 
	[<refinedstorage:storage_part:1>, <refinedstorage:storage_part:3>, <refinedstorage:storage_part:3>, <rebornstorage:storagepart:2>, <rebornstorage:storagepart:2>, <rebornstorage:storagepart:2>, <refinedstorage:storage_part:3>, <refinedstorage:storage_part:3>, <refinedstorage:storage_part:1>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <refinedstorage:storage_part>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Fluid Storage Disk
mods.extendedcrafting.TableCrafting.addShaped(0, <refinedstorage:fluid_storage_disk:4>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <mysticalagradditions:stuff:69>], 
	[<refinedstorage:fluid_storage_part:1>, <refinedstorage:fluid_storage_part:2>, <refinedstorage:fluid_storage_part:2>, <rebornstorage:storagepart:4>, <rebornstorage:storagepart:7>, <rebornstorage:storagepart:5>, <refinedstorage:fluid_storage_part:2>, <refinedstorage:fluid_storage_part:2>, <refinedstorage:fluid_storage_part:1>], 
	[<refinedstorage:fluid_storage_part:1>, <refinedstorage:fluid_storage_part:2>, <rebornstorage:storagepart:4>, <rebornstorage:storagepart:7>, <refinedstorage:storage_housing>, <rebornstorage:storagepart:7>, <rebornstorage:storagepart:5>, <refinedstorage:fluid_storage_part:2>, <refinedstorage:fluid_storage_part:1>], 
	[<refinedstorage:fluid_storage_part:1>, <rebornstorage:storagepart:4>, <rebornstorage:storagepart:7>, <refinedstorage:storage_housing>, <ore:ingotInfinity>, <refinedstorage:storage_housing>, <rebornstorage:storagepart:7>, <rebornstorage:storagepart:5>, <refinedstorage:fluid_storage_part:1>], 
	[<refinedstorage:fluid_storage_part:1>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:storage_housing>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:fluid_storage_part:1>], 
	[<refinedstorage:fluid_storage_part:1>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:fluid_storage_part:3>, <rebornstorage:storagepart:6>, <rebornstorage:storagepart:6>, <rebornstorage:storagepart:6>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:fluid_storage_part:1>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <refinedstorage:fluid_storage_part>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Chest
mods.extendedcrafting.TableCrafting.addShaped(0, <extrautils2:creativechest>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_creative>, <danknull:dank_null_6>, <botania:pool:1>, <ore:blockCosmicNeutronium>, <botania:manatablet>, <danknull:dank_null_6>, <storagedrawers:upgrade_creative>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <extendedcrafting:material:13>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <ore:ingotInfinity>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <extendedcrafting:material:13>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <extrautils2:creativeenergy>, <ore:blockCosmicNeutronium>, <ore:ingotInfinity>, <projecte:condenser_mk2>, <ore:ingotInfinity>, <ore:blockCosmicNeutronium>, <deepmoblearning:creative_model_learner>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <minecraft:enchanted_book>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <ore:ingotInfinity>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <minecraft:enchanted_book>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_creative>, <danknull:dank_null_6>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <danknull:dank_null_6>, <storagedrawers:upgrade_creative>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <avaritia:resource:5>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Capacitor
mods.extendedcrafting.TableCrafting.addShaped(0, <immersiveengineering:metal_device0:3>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <mysticalagradditions:stuff:69>], 
	[<immersiveengineering:metal_device0:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:wirecoil>, <immersiveengineering:wirecoil>, <immersiveengineering:wirecoil:2>, <immersiveengineering:wirecoil>, <immersiveengineering:wirecoil>, <immersiveengineering:metal_device0:2>, <immersiveengineering:metal_device0:1>], 
	[<immersiveengineering:metal_device0:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:wirecoil>, <immersiveengineering:wirecoil:2>, <ore:ingotCosmicNeutronium>, <immersiveengineering:wirecoil:2>, <immersiveengineering:wirecoil>, <immersiveengineering:metal_device0:2>, <immersiveengineering:metal_device0:1>], 
	[<immersiveengineering:metal_device0:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:wirecoil:2>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <immersiveengineering:wirecoil:2>, <immersiveengineering:metal_device0:2>, <immersiveengineering:metal_device0:1>], 
	[<immersiveengineering:metal_device0:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:wirecoil:1>, <immersiveengineering:wirecoil:2>, <ore:ingotCosmicNeutronium>, <immersiveengineering:wirecoil:2>, <immersiveengineering:wirecoil:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:metal_device0:1>], 
	[<immersiveengineering:metal_device0:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:wirecoil:1>, <immersiveengineering:wirecoil:1>, <immersiveengineering:wirecoil:2>, <immersiveengineering:wirecoil:1>, <immersiveengineering:wirecoil:1>, <immersiveengineering:metal_device0:2>, <immersiveengineering:metal_device0:1>], 
	[<mysticalagradditions:stuff:69>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <immersiveengineering:metal_device0>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Fluid Tank
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:machineblock2:11>.withTag({tier: 4}), [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mekanism:machineblock2:11>.withTag({tier: 1}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 1})], 
	[<mekanism:machineblock2:11>.withTag({tier: 1}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 1})], 
	[<mekanism:machineblock2:11>.withTag({tier: 1}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 1})], 
	[<mekanism:machineblock2:11>.withTag({tier: 1}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 1})], 
	[<mekanism:machineblock2:11>.withTag({tier: 1}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 3}), <mekanism:machineblock2:11>.withTag({tier: 2}), <mekanism:machineblock2:11>.withTag({tier: 1})], 
	[<mysticalagradditions:stuff:69>, <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}),<mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mekanism:machineblock2:11>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Energy Cube
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:energycube>.withTag({tier: 4}), [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mekanism:energycube>.withTag({tier: 1}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 1})], 
	[<mekanism:energycube>.withTag({tier: 1}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 1})], 
	[<mekanism:energycube>.withTag({tier: 1}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 1})], 
	[<mekanism:energycube>.withTag({tier: 1}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 1})], 
	[<mekanism:energycube>.withTag({tier: 1}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 2}), <mekanism:energycube>.withTag({tier: 1})], 
	[<mysticalagradditions:stuff:69>, <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mekanism:energycube>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Gas Tank
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:gastank>.withTag({tier: 4}), [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mekanism:gastank>.withTag({tier: 1}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 1})], 
	[<mekanism:gastank>.withTag({tier: 1}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 1})], 
	[<mekanism:gastank>.withTag({tier: 1}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 1})], 
	[<mekanism:gastank>.withTag({tier: 1}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 3}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 1})], 
	[<mekanism:gastank>.withTag({tier: 1}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 2}), <mekanism:gastank>.withTag({tier: 1})], 
	[<mysticalagradditions:stuff:69>, <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mekanism:gastank>.withTag({tier: 0}), <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Controller
mods.extendedcrafting.TableCrafting.addShaped(0, <refinedstorage:controller:1>.withTag({Energy: 32000}), [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <mysticalagradditions:stuff:69>], 
	[<refinedstorage:controller>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <refinedstorage:controller>], 
	[<ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <ore:ingotInfinity>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>, <ore:ingotCosmicNeutronium>], 
	[<refinedstorage:controller>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <refinedstorage:controller>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <refinedstorage:controller>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Ember Source
mods.extendedcrafting.TableCrafting.addShaped(0, <embers:creative_ember_source>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <mysticalagradditions:stuff:69>], 
	[<embers:ember_cluster>, <embers:ancient_motive_core>, <embers:ancient_motive_core>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <embers:ancient_motive_core>, <embers:ancient_motive_core>, <embers:ember_cluster>], 
	[<embers:ember_cluster>, <embers:ancient_motive_core>, <ore:ingotDawnstone>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotDawnstone>, <embers:ancient_motive_core>, <embers:ember_cluster>], 
	[<embers:ember_cluster>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <embers:ember_cluster>], 
	[<embers:ember_cluster>, <embers:ancient_motive_core>, <ore:ingotDawnstone>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotDawnstone>, <embers:ancient_motive_core>, <embers:ember_cluster>], 
	[<embers:ember_cluster>, <embers:ancient_motive_core>, <embers:ancient_motive_core>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <ore:ingotDawnstone>, <embers:ancient_motive_core>, <embers:ancient_motive_core>, <embers:ember_cluster>], 
	[<mysticalagradditions:stuff:69>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <embers:crystal_ember>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Wireless Crafting Grid
mods.extendedcrafting.TableCrafting.addShaped(0, <refinedstorageaddons:wireless_crafting_grid:1>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <mysticalagradditions:stuff:69>], 
	[<refinedstorageaddons:wireless_crafting_grid>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <refinedstorageaddons:wireless_crafting_grid>], 
	[<rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>], 
	[<rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>], 
	[<rebornstorage:multicrafter:1>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter:1>], 
	[<refinedstorageaddons:wireless_crafting_grid>, <rebornstorage:multicrafter:2>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter>, <rebornstorage:multicrafter:2>, <refinedstorageaddons:wireless_crafting_grid>], 
	[<mysticalagradditions:stuff:69>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <refinedstorageaddons:wireless_crafting_grid>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Storage Upgrade
mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:1>, <storagedrawers:upgrade_storage:2>, <storagedrawers:upgrade_storage:2>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:2>, <storagedrawers:upgrade_storage:2>, <storagedrawers:upgrade_storage:1>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:1>, <storagedrawers:upgrade_storage:2>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_storage:2>, <storagedrawers:upgrade_storage:1>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:1>, <storagedrawers:upgrade_storage:4>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:1>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:1>, <storagedrawers:upgrade_storage:3>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_storage:3>, <storagedrawers:upgrade_storage:1>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:1>, <storagedrawers:upgrade_storage:3>, <storagedrawers:upgrade_storage:3>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:3>, <storagedrawers:upgrade_storage:3>, <storagedrawers:upgrade_storage:1>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <storagedrawers:upgrade_storage>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Modifier
mods.extendedcrafting.TableCrafting.addShaped(0, <tconstruct:materials:50>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <mysticalagradditions:stuff:69>], 
	[<tconstruct:materials:14>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:14>], 
	[<tconstruct:materials:14>, <tconstruct:materials:16>, <tconstruct:materials:9>, <tconstruct:materials:11>, <tconstruct:materials:11>, <tconstruct:materials:11>, <tconstruct:materials:10>, <tconstruct:materials:16>, <tconstruct:materials:14>], 
	[<tconstruct:materials:14>, <tconstruct:materials:16>, <tconstruct:materials:9>, <tconstruct:materials:11>, <ore:ingotInfinity>, <tconstruct:materials:11>, <tconstruct:materials:10>, <tconstruct:materials:16>, <tconstruct:materials:14>], 
	[<tconstruct:materials:14>, <tconstruct:materials:16>, <tconstruct:materials:9>, <tconstruct:materials:11>, <tconstruct:materials:11>, <tconstruct:materials:11>, <tconstruct:materials:10>, <tconstruct:materials:16>, <tconstruct:materials:14>], 
	[<tconstruct:materials:14>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:16>, <tconstruct:materials:14>], 
	[<mysticalagradditions:stuff:69>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <tconstruct:materials:14>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Compressor
mods.extendedcrafting.TableCrafting.addShaped(0, <pneumaticcraft:creative_compressor>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <pneumaticcraft:air_compressor>, <mysticalagradditions:stuff:69>], 
	[<pneumaticcraft:air_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:liquid_compressor>, <pneumaticcraft:air_compressor>], 
	[<pneumaticcraft:liquid_compressor>, <pneumaticcraft:transistor>, <pneumaticcraft:pressure_tube>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <pneumaticcraft:advanced_pressure_tube>, <pneumaticcraft:capacitor>, <pneumaticcraft:liquid_compressor>], 
	[<pneumaticcraft:transistor>, <pneumaticcraft:transistor>, <pneumaticcraft:pressure_tube>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <pneumaticcraft:advanced_pressure_tube>, <pneumaticcraft:capacitor>, <pneumaticcraft:capacitor>], 
	[<pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:transistor>, <pneumaticcraft:pressure_tube>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <pneumaticcraft:advanced_pressure_tube>, <pneumaticcraft:capacitor>, <pneumaticcraft:advanced_liquid_compressor>], 
	[<pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_air_compressor>], 
	[<mysticalagradditions:stuff:69>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <pneumaticcraft:advanced_air_compressor>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Exchanger
mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:creative_exchanger>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <mysticalagradditions:stuff:69>], 
	[<ore:blockDraconiumAwakened>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconiumAwakened>], 
	[<ore:blockDraconiumAwakened>, <ore:blockDraconium>, <draconicevolution:chaotic_core>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <draconicevolution:chaotic_core>, <ore:blockDraconium>, <ore:blockDraconiumAwakened>], 
	[<ore:blockDraconiumAwakened>, <ore:blockDraconium>, <draconicevolution:chaotic_core>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <draconicevolution:chaotic_core>, <ore:blockDraconium>, <ore:blockDraconiumAwakened>], 
	[<ore:blockDraconiumAwakened>, <ore:blockDraconium>, <draconicevolution:chaotic_core>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <draconicevolution:chaotic_core>, <ore:blockDraconium>, <ore:blockDraconiumAwakened>], 
	[<ore:blockDraconiumAwakened>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconiumAwakened>], 
	[<mysticalagradditions:stuff:69>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <ore:blockDraconiumAwakened>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Mill
mods.extendedcrafting.TableCrafting.addShaped(0, <extrautils2:passivegenerator:6>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:2>, <mysticalagradditions:stuff:69>], 
	[<extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:2>], 
	[<extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:7>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:4>], 
	[<extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:7>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:8>], 
	[<extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:7>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:5>], 
	[<extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:3>], 
	[<mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:3>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Creative Vending Upgrade
mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative:1>, [
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorage:controller:1>, <mekanism:energycube>.withTag({tier: 4}), <mekanism:machineblock2:11>.withTag({tier: 4}), <immersiveengineering:metal_device0:3>, <mekanism:gastank>.withTag({tier: 4}), <pneumaticcraft:creative_compressor>, <extrautils2:passivegenerator:6>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <botania:manatablet>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <botania:pool:1>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <extrautils2:creativechest>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <draconicevolution:draconium_capacitor:2>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <refinedstorage:fluid_storage_disk:4>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <refinedstorageaddons:wireless_crafting_grid:1>, <storagedrawers:upgrade_creative>, <refinedstorage:storage_disk:4>, <tconstruct:materials:50>, <danknull:dank_null_6>, <draconicevolution:creative_exchanger>, <deepmoblearning:creative_model_learner>, <mysticalagradditions:stuff:69>], 
	[<mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>]
]);

//Drawer
mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:basicdrawers>.withTag({material: "oak"}), [
	[<storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <avaritia:resource:5>, <ore:blockInfinity>, <ore:blockCosmicNeutronium>, <ore:blockInfinity>, <avaritia:resource:5>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>], 
	[<storagedrawers:upgrade_creative:1>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <storagedrawers:upgrade_creative:1>], 
	[<avaritia:resource:5>, <ore:dreamwood>, <extrautils2:creativechest>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <extrautils2:creativechest>, <ore:dreamwood>, <avaritia:resource:5>], 
	[<ore:blockCosmicNeutronium>, <ore:dreamwood>, <mysticalagradditions:stuff:69>, <ore:blockUltimate>, <ore:blockUltimate>, <ore:blockUltimate>, <mysticalagradditions:stuff:69>, <ore:dreamwood>, <ore:blockCosmicNeutronium>], 
	[<ore:blockCosmicNeutronium>, <ore:dreamwood>, <mysticalagradditions:stuff:69>, <extendedcrafting:material:13>, <ore:logWood>, <extendedcrafting:material:13>, <mysticalagradditions:stuff:69>, <ore:dreamwood>, <ore:blockCosmicNeutronium>], 
	[<ore:blockCosmicNeutronium>, <ore:dreamwood>, <mysticalagradditions:stuff:69>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <mysticalagradditions:stuff:69>, <ore:dreamwood>, <ore:blockCosmicNeutronium>], 
	[<avaritia:resource:5>, <ore:dreamwood>, <extrautils2:creativechest>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <extrautils2:creativechest>, <ore:dreamwood>, <avaritia:resource:5>], 
	[<storagedrawers:upgrade_creative>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <ore:dreamwood>, <storagedrawers:upgrade_creative>], 
	[<storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>, <avaritia:resource:5>, <ore:blockCosmicNeutronium>, <ore:blockInfinity>, <ore:blockCosmicNeutronium>, <avaritia:resource:5>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_creative>]
]);